### Hourly Data Extract

In [188]:
import yfinance as yf
import pandas as pd

btc = yf.download("BTC-USD", interval="1h", period="730d")
btc.to_csv("btc_hourly.csv")

[*********************100%***********************]  1 of 1 completed

In [189]:
df = pd.read_csv('btc_hourly.csv')
df

,Price,Close,High,Low,Open,Volume
0,Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
1,Datetime,NaN,NaN,NaN,NaN,NaN
2,2024-05-01 00:00:00+00:00,60205.0,60763.9296875,60028.41796875,60612.921875,0
3,2024-05-01 01:00:00+00:00,60046.0390625,60314.19921875,59842.71875,60183.35546875,252477440
4,2024-05-01 02:00:00+00:00,59856.140625,60091.3671875,59546.796875,60066.85546875,0
...,...,...,...,...,...,...
17359,2026-04-30 17:00:00+00:00,76210.4296875,76296.7265625,76070.2734375,76205.5,0
17360,2026-04-30 18:00:00+00:00,76316.0,76442.03125,76165.5234375,76222.3671875,0
17361,2026-04-30 19:00:00+00:00,76381.3203125,76495.328125,76280.0,76296.75,0
17362,2026-04-30 20:00:00+00:00,76461.5,76537.7265625,76291.96875,76383.796875,105375744
17363,2026-04-30 21:00:00+00:00,76454.2578125,76507.2109375,76413.328125,76450.3125,64452608

In [190]:
df1 = df.drop(index=[0, 1]).reset_index(drop=True)

In [191]:
df1

,Price,Close,High,Low,Open,Volume
0,2024-05-01 00:00:00+00:00,60205.0,60763.9296875,60028.41796875,60612.921875,0
1,2024-05-01 01:00:00+00:00,60046.0390625,60314.19921875,59842.71875,60183.35546875,252477440
2,2024-05-01 02:00:00+00:00,59856.140625,60091.3671875,59546.796875,60066.85546875,0
3,2024-05-01 03:00:00+00:00,60180.30859375,60197.79296875,59857.140625,59857.140625,162103296
4,2024-05-01 04:00:00+00:00,60200.47265625,60255.40625,60141.25390625,60169.0078125,147656704
...,...,...,...,...,...,...
17357,2026-04-30 17:00:00+00:00,76210.4296875,76296.7265625,76070.2734375,76205.5,0
17358,2026-04-30 18:00:00+00:00,76316.0,76442.03125,76165.5234375,76222.3671875,0
17359,2026-04-30 19:00:00+00:00,76381.3203125,76495.328125,76280.0,76296.75,0
17360,2026-04-30 20:00:00+00:00,76461.5,76537.7265625,76291.96875,76383.796875,105375744
17361,2026-04-30 21:00:00+00:00,76454.2578125,76507.2109375,76413.328125,76450.3125,64452608

In [192]:
hourly = df1.rename(columns={"Price": "Date"})
hourly

,Date,Close,High,Low,Open,Volume
0,2024-05-01 00:00:00+00:00,60205.0,60763.9296875,60028.41796875,60612.921875,0
1,2024-05-01 01:00:00+00:00,60046.0390625,60314.19921875,59842.71875,60183.35546875,252477440
2,2024-05-01 02:00:00+00:00,59856.140625,60091.3671875,59546.796875,60066.85546875,0
3,2024-05-01 03:00:00+00:00,60180.30859375,60197.79296875,59857.140625,59857.140625,162103296
4,2024-05-01 04:00:00+00:00,60200.47265625,60255.40625,60141.25390625,60169.0078125,147656704
...,...,...,...,...,...,...
17357,2026-04-30 17:00:00+00:00,76210.4296875,76296.7265625,76070.2734375,76205.5,0
17358,2026-04-30 18:00:00+00:00,76316.0,76442.03125,76165.5234375,76222.3671875,0
17359,2026-04-30 19:00:00+00:00,76381.3203125,76495.328125,76280.0,76296.75,0
17360,2026-04-30 20:00:00+00:00,76461.5,76537.7265625,76291.96875,76383.796875,105375744
17361,2026-04-30 21:00:00+00:00,76454.2578125,76507.2109375,76413.328125,76450.3125,64452608

In [193]:
hourly.info()

<class 'pandas.DataFrame'>
RangeIndex: 17362 entries, 0 to 17361
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    17362 non-null  str
 1   Close   17362 non-null  str
 2   High    17362 non-null  str
 3   Low     17362 non-null  str
 4   Open    17362 non-null  str
 5   Volume  17362 non-null  str
dtypes: str(6)
memory usage: 814.0 KB

In [194]:
hourly.to_csv("hourly.csv")